---
title: "1st SCoPE Workshop"
---

**1st Social Conflict and Political Economy (SCoPE) Workshop**

*University of Sydney, 15 March 2024*

## Programme

- 9:30 AM – 9:50 AM: Morning Tea
- 9:50 AM – 10:00 AM: Opening remarks

MORNING SESSION

- 10:00 AM – 10:45 AM: Tobias Ide (Murdoch University): “Disasters, Armed Conflict Risks, and Rebel Governance”
- 10:45 AM – 11:30 AM: Eik Swee (University of Melbourne): “Political Goddess? The Electoral Impact of Religious Grassroots Organizations in Taiwan”
- 11:30 AM – 1:00 PM: Lunch

AFTERNOON SESSION

- 1:00 PM – 1:45 PM: Emilio Depetris-Chauvin (PUC–Chile): “(De facto) Historical Ethnic Borders and Contemporary Conflict in Africa”
- 1:45 PM – 2:30 PM: Haikun Zhan (University of Auckland): “Hidden Costs of War: Evidence from Nepal's Maoist Insurgency”
- 2:30 PM – 3:00 PM: Afternoon Tea
- 3:00 PM – 3:45 PM: Ashani Amarasinghe (University of Sydney): “(How) Do Natural Resources Drive International Relations?”
- 3:45 PM – 4:30 PM: Sascha Nanlohy (Institute for Economics & Peace): “Mapping Drivers of Violent Extremism and Conflict in the Central Sahel”


## Organizers 
David Ubilava, Ashani Amarasinghe, Justin Hastings, and Andrey Vasnev

## Acknowledgement 
The workshop organizers gratefully acknowledge support from the School of Economics at the University of Sydney and the Australian Research Council. 
